environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_YSs1nT
  projectIdentifier: TestDataSourceRemoteEnvironment_YSs1nT
  identifier: TestDataSourceRemoteEnvironment_YSs1nT
  tags: {}
  name: TestDataSourceRemoteEnvironment_YSs1nT
  type: PreProduction
