environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_9vo87l
  projectIdentifier: TestDataSourceRemoteEnvironment_9vo87l
  identifier: TestDataSourceRemoteEnvironment_9vo87l
  tags: {}
  name: TestDataSourceRemoteEnvironment_9vo87l
  type: PreProduction
