environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_U3w5rJ
  projectIdentifier: TestDataSourceRemoteEnvironment_U3w5rJ
  identifier: TestDataSourceRemoteEnvironment_U3w5rJ
  tags: {}
  name: TestDataSourceRemoteEnvironment_U3w5rJ
  type: PreProduction
