environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_XCz3kT
  projectIdentifier: TestDataSourceRemoteEnvironment_XCz3kT
  identifier: TestDataSourceRemoteEnvironment_XCz3kT
  tags: {}
  name: TestDataSourceRemoteEnvironment_XCz3kT
  type: PreProduction
