environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_2sH7PB
  projectIdentifier: TestDataSourceRemoteEnvironment_2sH7PB
  identifier: TestDataSourceRemoteEnvironment_2sH7PB
  tags: {}
  name: TestDataSourceRemoteEnvironment_2sH7PB
  type: PreProduction
