environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_rfBLPU
  projectIdentifier: TestDataSourceRemoteEnvironment_rfBLPU
  identifier: TestDataSourceRemoteEnvironment_rfBLPU
  tags: {}
  name: TestDataSourceRemoteEnvironment_rfBLPU
  type: PreProduction
