environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_8An6xn
  projectIdentifier: TestDataSourceRemoteEnvironment_8An6xn
  identifier: TestDataSourceRemoteEnvironment_8An6xn
  tags: {}
  name: TestDataSourceRemoteEnvironment_8An6xn
  type: PreProduction
