environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_CFvH7H
  projectIdentifier: TestDataSourceRemoteEnvironment_CFvH7H
  identifier: TestDataSourceRemoteEnvironment_CFvH7H
  tags: {}
  name: TestDataSourceRemoteEnvironment_CFvH7H
  type: PreProduction
