environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_etWROI
  projectIdentifier: TestDataSourceRemoteEnvironment_etWROI
  identifier: TestDataSourceRemoteEnvironment_etWROI
  tags: {}
  name: TestDataSourceRemoteEnvironment_etWROI
  type: PreProduction
