environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_NjfVnZ
  projectIdentifier: TestDataSourceRemoteEnvironment_NjfVnZ
  identifier: TestDataSourceRemoteEnvironment_NjfVnZ
  tags: {}
  name: TestDataSourceRemoteEnvironment_NjfVnZ
  type: PreProduction
