environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_lajYz6
  projectIdentifier: TestDataSourceRemoteEnvironment_lajYz6
  identifier: TestDataSourceRemoteEnvironment_lajYz6
  tags: {}
  name: TestDataSourceRemoteEnvironment_lajYz6
  type: PreProduction
