environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_y3qOKA
  projectIdentifier: TestDataSourceRemoteEnvironment_y3qOKA
  identifier: TestDataSourceRemoteEnvironment_y3qOKA
  tags: {}
  name: TestDataSourceRemoteEnvironment_y3qOKA
  type: PreProduction
