environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_3i0isD
  projectIdentifier: TestDataSourceRemoteEnvironment_3i0isD
  identifier: TestDataSourceRemoteEnvironment_3i0isD
  tags: {}
  name: TestDataSourceRemoteEnvironment_3i0isD
  type: PreProduction
