environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_fhlfzL
  projectIdentifier: TestDataSourceRemoteEnvironment_fhlfzL
  identifier: TestDataSourceRemoteEnvironment_fhlfzL
  tags: {}
  name: TestDataSourceRemoteEnvironment_fhlfzL
  type: PreProduction
