environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_Tq0G58
  projectIdentifier: TestDataSourceRemoteEnvironment_Tq0G58
  identifier: TestDataSourceRemoteEnvironment_Tq0G58
  tags: {}
  name: TestDataSourceRemoteEnvironment_Tq0G58
  type: PreProduction
