environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_8RVgdW
  projectIdentifier: TestDataSourceRemoteEnvironment_8RVgdW
  identifier: TestDataSourceRemoteEnvironment_8RVgdW
  tags: {}
  name: TestDataSourceRemoteEnvironment_8RVgdW
  type: PreProduction
