environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_4Fpd5W
  projectIdentifier: TestDataSourceRemoteEnvironment_4Fpd5W
  identifier: TestDataSourceRemoteEnvironment_4Fpd5W
  tags: {}
  name: TestDataSourceRemoteEnvironment_4Fpd5W
  type: PreProduction
