environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_R2QzOt
  projectIdentifier: TestDataSourceRemoteEnvironment_R2QzOt
  identifier: TestDataSourceRemoteEnvironment_R2QzOt
  tags: {}
  name: TestDataSourceRemoteEnvironment_R2QzOt
  type: PreProduction
