environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_hU6Wdo
  projectIdentifier: TestDataSourceRemoteEnvironment_hU6Wdo
  identifier: TestDataSourceRemoteEnvironment_hU6Wdo
  tags: {}
  name: TestDataSourceRemoteEnvironment_hU6Wdo
  type: PreProduction
