environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_eTOWiE
  projectIdentifier: TestDataSourceRemoteEnvironment_eTOWiE
  identifier: TestDataSourceRemoteEnvironment_eTOWiE
  tags: {}
  name: TestDataSourceRemoteEnvironment_eTOWiE
  type: PreProduction
