environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_iEYe1V
  projectIdentifier: TestDataSourceRemoteEnvironment_iEYe1V
  identifier: TestDataSourceRemoteEnvironment_iEYe1V
  tags: {}
  name: TestDataSourceRemoteEnvironment_iEYe1V
  type: PreProduction
