environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_V6S9jU
  projectIdentifier: TestDataSourceRemoteEnvironment_V6S9jU
  identifier: TestDataSourceRemoteEnvironment_V6S9jU
  tags: {}
  name: TestDataSourceRemoteEnvironment_V6S9jU
  type: PreProduction
