environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_fOo9QG
  projectIdentifier: TestDataSourceRemoteEnvironment_fOo9QG
  identifier: TestDataSourceRemoteEnvironment_fOo9QG
  tags: {}
  name: TestDataSourceRemoteEnvironment_fOo9QG
  type: PreProduction
