environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_y3T2PZ
  projectIdentifier: TestDataSourceRemoteEnvironment_y3T2PZ
  identifier: TestDataSourceRemoteEnvironment_y3T2PZ
  tags: {}
  name: TestDataSourceRemoteEnvironment_y3T2PZ
  type: PreProduction
