environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_JJBZtX
  projectIdentifier: TestDataSourceRemoteEnvironment_JJBZtX
  identifier: TestDataSourceRemoteEnvironment_JJBZtX
  tags: {}
  name: TestDataSourceRemoteEnvironment_JJBZtX
  type: PreProduction
