environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_l0U__a
  projectIdentifier: TestDataSourceRemoteEnvironment_l0U__a
  identifier: TestDataSourceRemoteEnvironment_l0U__a
  tags: {}
  name: TestDataSourceRemoteEnvironment_l0U__a
  type: PreProduction
