environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_JdIbma
  projectIdentifier: TestDataSourceRemoteEnvironment_JdIbma
  identifier: TestDataSourceRemoteEnvironment_JdIbma
  tags: {}
  name: TestDataSourceRemoteEnvironment_JdIbma
  type: PreProduction
