environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_vdD6zK
  projectIdentifier: TestDataSourceRemoteEnvironment_vdD6zK
  identifier: TestDataSourceRemoteEnvironment_vdD6zK
  tags: {}
  name: TestDataSourceRemoteEnvironment_vdD6zK
  type: PreProduction
