environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_q94Qxz
  projectIdentifier: TestDataSourceRemoteEnvironment_q94Qxz
  identifier: TestDataSourceRemoteEnvironment_q94Qxz
  tags: {}
  name: TestDataSourceRemoteEnvironment_q94Qxz
  type: PreProduction
