environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_3VF8eb
  projectIdentifier: TestDataSourceRemoteEnvironment_3VF8eb
  identifier: TestDataSourceRemoteEnvironment_3VF8eb
  tags: {}
  name: TestDataSourceRemoteEnvironment_3VF8eb
  type: PreProduction
