environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_t8Kevb
  projectIdentifier: TestDataSourceRemoteEnvironment_t8Kevb
  identifier: TestDataSourceRemoteEnvironment_t8Kevb
  tags: {}
  name: TestDataSourceRemoteEnvironment_t8Kevb
  type: PreProduction
