environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_q5QUjF
  projectIdentifier: TestDataSourceRemoteEnvironment_q5QUjF
  identifier: TestDataSourceRemoteEnvironment_q5QUjF
  tags: {}
  name: TestDataSourceRemoteEnvironment_q5QUjF
  type: PreProduction
