environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_dO9jg5
  projectIdentifier: TestDataSourceRemoteEnvironment_dO9jg5
  identifier: TestDataSourceRemoteEnvironment_dO9jg5
  tags: {}
  name: TestDataSourceRemoteEnvironment_dO9jg5
  type: PreProduction
