infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Kj8S9Y"
   identifier: "TestDataSourceRemoteInfrastrucutre_Kj8S9Y"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Kj8S9Y
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
