infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_QX1dDK"
   identifier: "TestDataSourceRemoteInfrastrucutre_QX1dDK"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_QX1dDK
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
