infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Tjx7tk"
   identifier: "TestDataSourceRemoteInfrastrucutre_Tjx7tk"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Tjx7tk
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
