infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_TMa2vv"
   identifier: "TestDataSourceRemoteInfrastrucutre_TMa2vv"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_TMa2vv
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
