infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_R7pfTp"
   identifier: "TestDataSourceRemoteInfrastrucutre_R7pfTp"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_R7pfTp
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
