infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_6R1gk6"
   identifier: "TestDataSourceRemoteInfrastrucutre_6R1gk6"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_6R1gk6
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
