infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_5AEGYn"
   identifier: "TestDataSourceRemoteInfrastrucutre_5AEGYn"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_5AEGYn
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
