infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_2Cr3t0"
   identifier: "TestDataSourceRemoteInfrastrucutre_2Cr3t0"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_2Cr3t0
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
