infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_mmB4Ma"
   identifier: "TestDataSourceRemoteInfrastrucutre_mmB4Ma"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_mmB4Ma
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
