infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_df1ARc"
   identifier: "TestDataSourceRemoteInfrastrucutre_df1ARc"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_df1ARc
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
