infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_6mPbd7"
   identifier: "TestDataSourceRemoteInfrastrucutre_6mPbd7"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_6mPbd7
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
