infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_0qNi35"
   identifier: "TestDataSourceRemoteInfrastrucutre_0qNi35"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_0qNi35
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
