infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_B9psbT"
   identifier: "TestDataSourceRemoteInfrastrucutre_B9psbT"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_B9psbT
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
