infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Bj1eHb"
   identifier: "TestDataSourceRemoteInfrastrucutre_Bj1eHb"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Bj1eHb
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
