infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_ug_ZT1"
   identifier: "TestDataSourceRemoteInfrastrucutre_ug_ZT1"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_ug_ZT1
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
