infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Z3NIaT"
   identifier: "TestDataSourceRemoteInfrastrucutre_Z3NIaT"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Z3NIaT
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
