infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_fVw66t"
   identifier: "TestDataSourceRemoteInfrastrucutre_fVw66t"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_fVw66t
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
