infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Qz_8Mg"
   identifier: "TestDataSourceRemoteInfrastrucutre_Qz_8Mg"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Qz_8Mg
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
