infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_2lqw_V"
   identifier: "TestDataSourceRemoteInfrastrucutre_2lqw_V"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_2lqw_V
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
