infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_iZ5_pa"
   identifier: "TestDataSourceRemoteInfrastrucutre_iZ5_pa"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_iZ5_pa
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
