infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_qA8tJ_"
   identifier: "TestDataSourceRemoteInfrastrucutre_qA8tJ_"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_qA8tJ_
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
