infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_pH9U3T"
   identifier: "TestDataSourceRemoteInfrastrucutre_pH9U3T"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_pH9U3T
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
