infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Z61R8U"
   identifier: "TestDataSourceRemoteInfrastrucutre_Z61R8U"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Z61R8U
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
