infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_emS2uw"
   identifier: "TestDataSourceRemoteInfrastrucutre_emS2uw"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_emS2uw
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
