infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Ombxot"
   identifier: "TestDataSourceRemoteInfrastrucutre_Ombxot"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Ombxot
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
