infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_vq2OTp"
   identifier: "TestDataSourceRemoteInfrastrucutre_vq2OTp"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_vq2OTp
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
