infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_4nWX9r"
   identifier: "TestDataSourceRemoteInfrastrucutre_4nWX9r"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_4nWX9r
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
