infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_NZRpA8"
   identifier: "TestDataSourceRemoteInfrastrucutre_NZRpA8"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_NZRpA8
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
