infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_D3ziSp"
   identifier: "TestDataSourceRemoteInfrastrucutre_D3ziSp"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_D3ziSp
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
