infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_VCuXBc"
   identifier: "TestDataSourceRemoteInfrastrucutre_VCuXBc"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_VCuXBc
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
