infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_grNoJK"
   identifier: "TestDataSourceRemoteInfrastrucutre_grNoJK"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_grNoJK
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
