infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_MBdZ9n"
   identifier: "TestDataSourceRemoteInfrastrucutre_MBdZ9n"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_MBdZ9n
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
