infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_6L9uGY"
   identifier: "TestDataSourceRemoteInfrastrucutre_6L9uGY"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_6L9uGY
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
