infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_o0QASt"
   identifier: "TestDataSourceRemoteInfrastrucutre_o0QASt"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_o0QASt
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
