infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_8nbr9o"
   identifier: "TestDataSourceRemoteInfrastrucutre_8nbr9o"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_8nbr9o
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
