infrastructureDefinition:
   name: "TestResourceRemoteInfrastructure"
   identifier: "TestResourceRemoteInfrastructure_vrvyf"
   description: ""
   tags:
     asda: ""
   environmentRef: TestResourceRemoteInfrastructure_vrvyf
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
   allowSimultaneousDeployments: false
