infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_wRDuKZ"
   identifier: "TestDataSourceRemoteInfrastrucutre_wRDuKZ"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_wRDuKZ
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
