infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_t0h1Nv"
   identifier: "TestDataSourceRemoteInfrastrucutre_t0h1Nv"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_t0h1Nv
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
