infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_545TVp"
   identifier: "TestDataSourceRemoteInfrastrucutre_545TVp"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_545TVp
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
