infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_xVqw7K"
   identifier: "TestDataSourceRemoteInfrastrucutre_xVqw7K"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_xVqw7K
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
