infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_JCLy7I"
   identifier: "TestDataSourceRemoteInfrastrucutre_JCLy7I"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_JCLy7I
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
