infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Y7PKjZ"
   identifier: "TestDataSourceRemoteInfrastrucutre_Y7PKjZ"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Y7PKjZ
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
