infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_NPjQDQ"
   identifier: "TestDataSourceRemoteInfrastrucutre_NPjQDQ"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_NPjQDQ
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
