infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_8Jp5IK"
   identifier: "TestDataSourceRemoteInfrastrucutre_8Jp5IK"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_8Jp5IK
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
