infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_bBPjZ0"
   identifier: "TestDataSourceRemoteInfrastrucutre_bBPjZ0"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_bBPjZ0
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
