infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_9hmUoT"
   identifier: "TestDataSourceRemoteInfrastrucutre_9hmUoT"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_9hmUoT
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
