infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_7qkWKt"
   identifier: "TestDataSourceRemoteInfrastrucutre_7qkWKt"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_7qkWKt
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
