infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_QmO7SF"
   identifier: "TestDataSourceRemoteInfrastrucutre_QmO7SF"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_QmO7SF
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
