infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_j8Ry61"
   identifier: "TestDataSourceRemoteInfrastrucutre_j8Ry61"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_j8Ry61
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
