infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_TmOtVF"
   identifier: "TestDataSourceRemoteInfrastrucutre_TmOtVF"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_TmOtVF
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
