infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_UmwnfV"
   identifier: "TestDataSourceRemoteInfrastrucutre_UmwnfV"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_UmwnfV
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
