infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Pb9AGI"
   identifier: "TestDataSourceRemoteInfrastrucutre_Pb9AGI"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Pb9AGI
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
