infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_xhmAc3"
   identifier: "TestDataSourceRemoteInfrastrucutre_xhmAc3"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_xhmAc3
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
