infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_c8mdaZ"
   identifier: "TestDataSourceRemoteInfrastrucutre_c8mdaZ"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_c8mdaZ
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
