infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_TZh_po"
   identifier: "TestDataSourceRemoteInfrastrucutre_TZh_po"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_TZh_po
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
