infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_xKDr_f"
   identifier: "TestDataSourceRemoteInfrastrucutre_xKDr_f"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_xKDr_f
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
