infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_5x88gs"
   identifier: "TestDataSourceRemoteInfrastrucutre_5x88gs"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_5x88gs
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
