infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_pA6fRt"
   identifier: "TestDataSourceRemoteInfrastrucutre_pA6fRt"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_pA6fRt
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
