infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_8erL0v"
   identifier: "TestDataSourceRemoteInfrastrucutre_8erL0v"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_8erL0v
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
