infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_pX2bbi"
   identifier: "TestDataSourceRemoteInfrastrucutre_pX2bbi"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_pX2bbi
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
