infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_BZFYxq"
   identifier: "TestDataSourceRemoteInfrastrucutre_BZFYxq"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_BZFYxq
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
