infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_ol8m83"
   identifier: "TestDataSourceRemoteInfrastrucutre_ol8m83"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_ol8m83
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
