infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_ih0PFY"
   identifier: "TestDataSourceRemoteInfrastrucutre_ih0PFY"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_ih0PFY
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
