infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_JAEe_6"
   identifier: "TestDataSourceRemoteInfrastrucutre_JAEe_6"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_JAEe_6
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
