infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_Eoymr1"
   identifier: "TestDataSourceRemoteInfrastrucutre_Eoymr1"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_Eoymr1
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
