infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_uT7Fnq"
   identifier: "TestDataSourceRemoteInfrastrucutre_uT7Fnq"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_uT7Fnq
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
