infrastructureDefinition:
   name: "TestDataSourceRemoteInfrastrucutre_s5M2U7"
   identifier: "TestDataSourceRemoteInfrastrucutre_s5M2U7"
   description: ""
   tags:
     asda: ""
   environmentRef: TestDataSourceRemoteInfrastrucutre_s5M2U7
   deploymentType: Kubernetes
   type: KubernetesDirect
   spec:
    connectorRef: "<+input>"
    namespace: "<+input>"
    releaseName: "<+input>"
